export const CATEGORIES = ['All', 'Featured', 'Portraits', 'Products & Brand', 'Editing', 'Creative', 'Video'];

export const BLUEPRINTS = [
  // ─── Featured ───
  {
    id: 'amber-haze-portrait',
    title: 'Amber Haze Portrait',
    description: 'Generate dreamy portrait photos with warm amber tones, soft bokeh, and cinematic haze.',
    category: 'Featured',
    type: 'image',
    cover: '/images/styles/baroque-art.jpg',
    steps: [
      { id: 'reference', label: 'Add Photo', type: 'image', required: true, hint: 'Upload a portrait or face photo' },
      { id: 'prompt', label: 'Details', type: 'text', required: false, hint: 'Any additional style directions (optional)' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Transform this portrait into a warm amber-toned photograph with soft bokeh, golden haze, and cinematic lighting. Keep the face and features consistent.',
  },
  {
    id: 'style-transfer',
    title: 'Style Transfer',
    description: 'Apply any art style to your images — from impressionism to cyberpunk to watercolor.',
    category: 'Featured',
    type: 'image',
    cover: '/images/styles/impressionism-art.jpg',
    steps: [
      { id: 'reference', label: 'Source Image', type: 'image', required: true, hint: 'Upload the image to restyle' },
      { id: 'style', label: 'Art Style', type: 'style-picker', required: true },
      { id: 'prompt', label: 'Details', type: 'text', required: false, hint: 'Additional instructions (optional)' },
    ],
    defaultModel: 'flux',
    systemPrompt: 'Recreate this image in the specified art style while preserving the subject and composition.',
  },
  {
    id: 'product-spin-video',
    title: 'Product Spin Video',
    description: 'Create a smooth 360° spin video of your product for marketing and e-commerce.',
    category: 'Featured',
    type: 'video',
    cover: '/images/styles/minimalism-art.jpg',
    steps: [
      { id: 'reference', label: 'Product Image', type: 'image', required: true, hint: 'Upload a clean product photo' },
      { id: 'prompt', label: 'Scene', type: 'text', required: false, hint: 'Background description (optional, defaults to studio white)' },
    ],
    defaultModel: 'wan',
    systemPrompt: 'Create a smooth 360-degree rotation video of this product on a clean studio background with professional lighting.',
  },

  // ─── Editing ───
  {
    id: 'object-remover',
    title: 'Object Remover',
    description: 'Remove unwanted objects, people, or elements from your images seamlessly.',
    category: 'Editing',
    type: 'image',
    cover: '/images/styles/digital-painting.jpg',
    steps: [
      { id: 'reference', label: 'Upload Image', type: 'image', required: true, hint: 'Upload the image to edit' },
      { id: 'prompt', label: 'What to Remove', type: 'text', required: true, hint: 'Describe what to remove, e.g. "Remove the person on the left"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Remove the described element from this image. Fill the area naturally with the surrounding background. Keep everything else unchanged.',
  },
  {
    id: 'warm-relight',
    title: 'Warm Relight',
    description: 'Relight any photo with warm, golden, cinematic lighting for a professional look.',
    category: 'Editing',
    type: 'image',
    cover: '/images/styles/renaissance-art.jpg',
    steps: [
      { id: 'reference', label: 'Upload Photo', type: 'image', required: true, hint: 'Upload the photo to relight' },
      { id: 'prompt', label: 'Lighting Style', type: 'text', required: false, hint: 'e.g. "Golden hour sunlight from the left" (optional)' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Relight this photograph with warm, golden, cinematic lighting. Add natural light falloff, soft shadows, and a warm color temperature while preserving the subject.',
  },
  {
    id: 'instant-outpaint',
    title: 'Instant Outpaint',
    description: 'Extend your images beyond their borders — expand any photo in any direction.',
    category: 'Editing',
    type: 'image',
    cover: '/images/styles/surrealism-art.jpg',
    steps: [
      { id: 'reference', label: 'Upload Image', type: 'image', required: true, hint: 'Upload the image to expand' },
      { id: 'prompt', label: 'Expansion Details', type: 'text', required: true, hint: 'Describe what should appear in the expanded area' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Expand this image outward, extending the scene naturally. Generate new content that seamlessly blends with the existing image edges.',
  },
  {
    id: 'edit-in-a-click',
    title: 'Edit Images in a Click',
    description: 'Make quick edits to any image — change colors, add elements, modify scenes.',
    category: 'Editing',
    type: 'image',
    cover: '/images/styles/pop-art.jpeg',
    steps: [
      { id: 'reference', label: 'Upload Image', type: 'image', required: true, hint: 'Upload the image to edit' },
      { id: 'prompt', label: 'Edit Instructions', type: 'text', required: true, hint: 'Describe the changes you want, e.g. "Make the sky sunset orange"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Apply the described edit to this image. Make the change look natural and seamless.',
  },

  // ─── Products & Brand ───
  {
    id: 'instant-brand-kit',
    title: 'Instant Brand Kit',
    description: 'Generate a cohesive set of brand visuals from your logo — social posts, banners, cards.',
    category: 'Products & Brand',
    type: 'image',
    cover: '/images/styles/abstract.jpeg',
    steps: [
      { id: 'reference', label: 'Upload Logo', type: 'image', required: true, hint: 'Upload your brand logo or mark' },
      { id: 'prompt', label: 'Brand Style', type: 'text', required: true, hint: 'Describe your brand aesthetic, e.g. "Minimal, tech, dark mode with blue accents"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Create a branded visual asset using this logo. Integrate the logo naturally into a professional marketing material. Match the described brand aesthetic.',
  },
  {
    id: 'product-in-scene',
    title: 'Product in Scene',
    description: 'Place your product into beautiful lifestyle scenes for marketing shots.',
    category: 'Products & Brand',
    type: 'image',
    cover: '/images/styles/baroque-art.jpg',
    steps: [
      { id: 'reference', label: 'Product Photo', type: 'image', required: true, hint: 'Upload a clean product photo' },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'e.g. "On a marble kitchen counter with morning sunlight and fresh flowers"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Place this product naturally into the described lifestyle scene. Use realistic lighting, shadows, and reflections. The product should look like it belongs in the scene.',
  },
  {
    id: 'product-studio-photoshoot',
    title: 'Product Studio Photoshoot',
    description: 'Generate professional studio-quality product photography with perfect lighting.',
    category: 'Products & Brand',
    type: 'image',
    cover: '/images/styles/minimalism-art.jpg',
    steps: [
      { id: 'reference', label: 'Product Image', type: 'image', required: true, hint: 'Upload your product photo' },
      { id: 'prompt', label: 'Setup', type: 'text', required: false, hint: 'e.g. "White seamless backdrop, soft diffused light" (optional)' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Create a professional studio product photograph. Use clean backdrop, perfect studio lighting with soft shadows, and commercial-grade composition.',
  },

  // ─── Portraits ───
  {
    id: 'bold-fisheye-portrait',
    title: 'Bold Fisheye Portrait',
    description: 'Create eye-catching portraits with dramatic fisheye lens distortion and bold colors.',
    category: 'Portraits',
    type: 'image',
    cover: '/images/styles/cyberpunk-art.jpg',
    steps: [
      { id: 'reference', label: 'Upload Portrait', type: 'image', required: true, hint: 'Upload a face or portrait photo' },
      { id: 'prompt', label: 'Style', type: 'text', required: false, hint: 'Additional style directions (optional)' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Transform this portrait using a dramatic fisheye lens effect with bold, saturated colors. Create an eye-catching, editorial-style composition.',
  },
  {
    id: 'change-hairstyle',
    title: 'Change My Hairstyle',
    description: 'Try different hairstyles, colors, and cuts on your photo before committing.',
    category: 'Portraits',
    type: 'image',
    cover: '/images/styles/art-nouveau.jpeg',
    steps: [
      { id: 'reference', label: 'Upload Photo', type: 'image', required: true, hint: 'Upload a clear front-facing portrait' },
      { id: 'prompt', label: 'New Hairstyle', type: 'text', required: true, hint: 'e.g. "Short bob cut with platinum blonde highlights" or "Long curly red hair"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Change the hairstyle in this photo to match the description. Keep the face, skin, and everything else identical. Only modify the hair.',
  },
  {
    id: 'outfit-inspo',
    title: 'Outfit Inspo',
    description: 'Visualize different outfits and styles on your photo for fashion inspiration.',
    category: 'Portraits',
    type: 'image',
    cover: '/images/styles/vaporwave-art.jpg',
    steps: [
      { id: 'reference', label: 'Upload Photo', type: 'image', required: true, hint: 'Upload a full-body or upper-body photo' },
      { id: 'prompt', label: 'Outfit Description', type: 'text', required: true, hint: 'e.g. "Casual streetwear with oversized hoodie and cargo pants" or "Elegant red evening gown"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Change the outfit/clothing in this photo to match the description. Keep the person, face, body proportions, and background identical. Only modify the clothing and accessories.',
  },

  // ─── Creative ───
  {
    id: 'moodboard-maker',
    title: 'Moodboard Maker',
    description: 'Generate visual moodboards for projects, interior design, fashion, or branding.',
    category: 'Creative',
    type: 'image',
    cover: '/images/styles/synthwave-art.jpg',
    steps: [
      { id: 'reference', label: 'Inspiration', type: 'image', required: false, hint: 'Upload a reference image (optional)' },
      { id: 'prompt', label: 'Theme', type: 'text', required: true, hint: 'e.g. "Minimalist Scandinavian interior with warm wood and white tones"' },
    ],
    defaultModel: 'flux',
    systemPrompt: 'Create a professional moodboard collage with multiple visual elements, textures, colors, and typography that represent the described theme. Layout should feel curated and editorial.',
  },
  {
    id: 'font-matcher',
    title: 'Font Matcher',
    description: 'Generate visual typography explorations and find the perfect font pairing for your project.',
    category: 'Creative',
    type: 'image',
    cover: '/images/styles/pop-art.jpeg',
    steps: [
      { id: 'reference', label: 'Brand/Logo', type: 'image', required: false, hint: 'Upload your brand asset (optional)' },
      { id: 'prompt', label: 'Typography Brief', type: 'text', required: true, hint: 'e.g. "Modern serif heading with clean sans-serif body text, luxury feel"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Create a typography showcase/specimen sheet showing the described font pairing and style. Include sample headlines, body text, and decorative elements that demonstrate the typographic system.',
  },
  {
    id: 'furnish-my-space',
    title: 'Furnish My Space',
    description: 'Reimagine your room with new furniture, decor, and interior design styles.',
    category: 'Creative',
    type: 'image',
    cover: '/images/styles/renaissance.jpeg',
    steps: [
      { id: 'reference', label: 'Room Photo', type: 'image', required: true, hint: 'Upload a photo of your room or space' },
      { id: 'prompt', label: 'Design Style', type: 'text', required: true, hint: 'e.g. "Modern minimalist with mid-century furniture, warm lighting, indoor plants"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Redesign this room interior with the described style. Replace or add furniture, decor, and styling while keeping the room structure and architecture. Make it look like a real interior design photo.',
  },
  {
    id: 'storybook-sequence',
    title: 'Storybook Sequence',
    description: 'Create consistent illustrated scenes for storytelling with the same characters.',
    category: 'Creative',
    type: 'image',
    cover: '/images/styles/art-nouveau.jpeg',
    steps: [
      { id: 'reference', label: 'Character Ref', type: 'image', required: true, hint: 'Upload your main character reference' },
      { id: 'style', label: 'Style', type: 'style-picker', required: false },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'Describe this scene in the story' },
    ],
    defaultModel: 'kontext',
    systemPrompt: 'Create a storybook illustration. Keep the character consistent with the reference. Use a warm, illustrative style suitable for storytelling.',
  },
  {
    id: 'consistent-character',
    title: 'Consistent Character',
    description: 'Generate images of the same character in new situations, environments, and poses.',
    category: 'Creative',
    type: 'image',
    cover: '/images/styles/digital-painting.jpg',
    steps: [
      { id: 'reference', label: 'Add Image', type: 'image', required: true, hint: 'Upload your character image' },
      { id: 'style', label: 'Style', type: 'style-picker', required: false },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'Describe the new scene for your character' },
    ],
    defaultModel: 'kontext',
    systemPrompt: 'Keep the character from the reference image exactly consistent. Change only the scene, pose, and environment as described.',
  },

  // ─── Video ───
  {
    id: 'video-scene',
    title: 'Video Scene',
    description: 'Generate short cinematic video clips from a reference image or text description.',
    category: 'Video',
    type: 'video',
    cover: '/images/styles/synthwave-art.jpg',
    steps: [
      { id: 'reference', label: 'First Frame', type: 'image', required: false, hint: 'Upload a reference image (optional)' },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'Describe the video scene and motion' },
    ],
    defaultModel: 'wan',
    systemPrompt: 'Generate a smooth, cinematic video clip based on the description.',
  },
  {
    id: 'landscape-video',
    title: 'Landscape Video',
    description: 'Create breathtaking landscape flyover and nature videos with cinematic motion.',
    category: 'Video',
    type: 'video',
    cover: '/images/styles/renaissance-art.jpg',
    steps: [
      { id: 'reference', label: 'Landscape', type: 'image', required: false, hint: 'Upload a landscape photo (optional)' },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'e.g. "Slow aerial flyover of misty mountains at sunrise"' },
    ],
    defaultModel: 'veo',
    systemPrompt: 'Create a cinematic landscape video with smooth camera motion and dramatic natural lighting.',
  },
];

export const STYLE_PRESETS = [
  { id: 'dynamic', label: 'Dynamic', image: '/images/styles/digital-painting.jpg' },
  { id: 'cinematic', label: 'Cinematic', image: '/images/styles/baroque-art.jpg' },
  { id: 'cyberpunk', label: 'Cyberpunk', image: '/images/styles/cyberpunk-art.jpg' },
  { id: 'anime', label: 'Anime', image: '/images/styles/synthwave-art.jpg' },
  { id: 'impressionist', label: 'Impressionist', image: '/images/styles/impressionism-art.jpg' },
  { id: 'surreal', label: 'Surreal', image: '/images/styles/surrealism-art.jpg' },
  { id: 'minimalist', label: 'Minimalist', image: '/images/styles/minimalism-art.jpg' },
  { id: 'pop-art', label: 'Pop Art', image: '/images/styles/pop-art.jpeg' },
  { id: 'vaporwave', label: 'Vaporwave', image: '/images/styles/vaporwave-art.jpg' },
  { id: 'renaissance', label: 'Renaissance', image: '/images/styles/renaissance-art.jpg' },
  { id: 'art-nouveau', label: 'Art Nouveau', image: '/images/styles/art-nouveau.jpeg' },
  { id: 'abstract', label: 'Abstract', image: '/images/styles/abstract.jpeg' },
];
