export const CATEGORIES = ['All', 'Ideate', 'Characters', 'Marketing', 'Photography', 'Video'];

export const BLUEPRINTS = [
  {
    id: 'consistent-character',
    title: 'Consistent Character',
    description: 'Generate images of the same character in new situations, environments, and poses.',
    category: 'Characters',
    type: 'image',
    cover: '/images/styles/digital-painting.jpg',
    samples: ['/images/styles/renaissance.jpeg', '/images/styles/baroque-art.jpg'],
    steps: [
      { id: 'reference', label: 'Add Image', type: 'image', required: true, hint: 'Upload your character image (PNG/JPG up to 5MB)' },
      { id: 'style', label: 'Style', type: 'style-picker', required: false },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'Describe the new scene for your character' },
    ],
    defaultModel: 'kontext',
    systemPrompt: 'Keep the character from the reference image exactly consistent. Change only the scene, pose, and environment as described.',
  },
  {
    id: 'brand-mockup',
    title: 'Brand Mockup',
    description: 'Upload logos, graphics or designs and preview them on packaging, apparel, and mockups.',
    category: 'Marketing',
    type: 'image',
    cover: '/images/styles/minimalism-art.jpg',
    samples: ['/images/styles/pop-art.jpeg', '/images/styles/abstract.jpeg'],
    steps: [
      { id: 'reference', label: 'Add Logo', type: 'image', required: true, hint: 'Upload your logo or design asset' },
      { id: 'prompt', label: 'Describe Mockup', type: 'text', required: true, hint: 'e.g. "Coffee cup mockup on a wooden table, morning light"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Place the uploaded logo/design onto the described mockup scene. Keep the design accurate and readable.',
  },
  {
    id: 'sketch-to-image',
    title: 'Sketch to Image',
    description: 'Transform rough sketches and drawings into polished, detailed images.',
    category: 'Ideate',
    type: 'image',
    cover: '/images/styles/impressionism-art.jpg',
    samples: ['/images/styles/art-nouveau.jpeg'],
    steps: [
      { id: 'reference', label: 'Upload Sketch', type: 'image', required: true, hint: 'Upload your sketch or drawing' },
      { id: 'style', label: 'Style', type: 'style-picker', required: false },
      { id: 'prompt', label: 'Describe', type: 'text', required: true, hint: 'Describe the desired output style and details' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Transform this sketch into a polished, detailed image while preserving the original composition and subject matter.',
  },
  {
    id: 'product-photography',
    title: 'Product Photography',
    description: 'Generate professional product shots with studio lighting and styled backgrounds.',
    category: 'Photography',
    type: 'image',
    cover: '/images/styles/baroque-art.jpg',
    samples: ['/images/styles/renaissance-art.jpg'],
    steps: [
      { id: 'reference', label: 'Product Image', type: 'image', required: true, hint: 'Upload your product photo' },
      { id: 'prompt', label: 'Scene Setup', type: 'text', required: true, hint: 'e.g. "Luxury marble surface, soft studio lighting, minimalist background"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Create a professional product photography shot. Place the product naturally in the described scene with studio-quality lighting.',
  },
  {
    id: 'style-exploration',
    title: 'Style Exploration',
    description: 'Apply different art styles to your images — from impressionism to cyberpunk.',
    category: 'Ideate',
    type: 'image',
    cover: '/images/styles/cyberpunk-art.jpg',
    samples: ['/images/styles/vaporwave-art.jpg', '/images/styles/synthwave-art.jpg'],
    steps: [
      { id: 'reference', label: 'Source Image', type: 'image', required: true, hint: 'Upload the image to restyle' },
      { id: 'style', label: 'Art Style', type: 'style-picker', required: true },
      { id: 'prompt', label: 'Details', type: 'text', required: false, hint: 'Any additional instructions (optional)' },
    ],
    defaultModel: 'flux',
    systemPrompt: 'Recreate this image in the specified art style while preserving the subject and composition.',
  },
  {
    id: 'storybook-sequence',
    title: 'Storybook Sequence',
    description: 'Create a series of consistent illustrations for storytelling with the same characters.',
    category: 'Characters',
    type: 'image',
    cover: '/images/styles/art-nouveau.jpeg',
    samples: ['/images/styles/impressionism-art.jpg'],
    steps: [
      { id: 'reference', label: 'Character Ref', type: 'image', required: true, hint: 'Upload your main character reference' },
      { id: 'style', label: 'Style', type: 'style-picker', required: false },
      { id: 'prompt', label: 'Scene Description', type: 'text', required: true, hint: 'Describe this scene in the story' },
    ],
    defaultModel: 'kontext',
    systemPrompt: 'Create a storybook illustration. Keep the character consistent with the reference. Use a warm, illustrative style suitable for storytelling.',
  },
  {
    id: 'video-scene',
    title: 'Video Scene',
    description: 'Generate short video clips from a reference image or text description.',
    category: 'Video',
    type: 'video',
    cover: '/images/styles/synthwave-art.jpg',
    samples: ['/images/styles/cyberpunk-art.jpg'],
    steps: [
      { id: 'reference', label: 'First Frame', type: 'image', required: false, hint: 'Upload a reference image (optional)' },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'Describe the video scene and motion' },
    ],
    defaultModel: 'wan',
    systemPrompt: 'Generate a smooth, cinematic video clip based on the description.',
  },
  {
    id: 'character-sheet',
    title: 'Character Sheet',
    description: 'Generate multiple views and expressions of a character for reference sheets.',
    category: 'Characters',
    type: 'image',
    cover: '/images/styles/renaissance.jpeg',
    samples: ['/images/styles/digital-painting.jpg'],
    steps: [
      { id: 'reference', label: 'Character', type: 'image', required: true, hint: 'Upload your character design' },
      { id: 'prompt', label: 'Views', type: 'text', required: true, hint: 'e.g. "Front view, side view, back view, multiple expressions"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Create a character reference sheet showing the character from multiple angles and with different expressions. Keep the character design perfectly consistent.',
  },
  {
    id: 'logo-variations',
    title: 'Logo Variations',
    description: 'Generate creative variations and applications of your logo design.',
    category: 'Marketing',
    type: 'image',
    cover: '/images/styles/pop-art.jpeg',
    samples: ['/images/styles/minimalism-art.jpg'],
    steps: [
      { id: 'reference', label: 'Logo', type: 'image', required: true, hint: 'Upload your logo' },
      { id: 'prompt', label: 'Variation', type: 'text', required: true, hint: 'e.g. "3D metallic version on dark background" or "Embossed on leather"' },
    ],
    defaultModel: 'gptimage',
    systemPrompt: 'Create a variation of this logo as described. Keep the core design elements recognizable.',
  },
  {
    id: 'social-media-kit',
    title: 'Social Media Kit',
    description: 'Generate cohesive social media visuals — posts, stories, banners.',
    category: 'Marketing',
    type: 'image',
    cover: '/images/styles/vaporwave-art.jpg',
    samples: ['/images/styles/abstract.jpeg'],
    steps: [
      { id: 'reference', label: 'Brand Asset', type: 'image', required: false, hint: 'Upload a brand image or logo (optional)' },
      { id: 'prompt', label: 'Content', type: 'text', required: true, hint: 'e.g. "Instagram post announcing summer sale, vibrant tropical theme"' },
    ],
    defaultModel: 'flux',
    systemPrompt: 'Create a social media visual that is eye-catching and on-brand. Use modern design trends.',
  },
  {
    id: 'art-style-transfer',
    title: 'Art Style Transfer',
    description: 'Transform photos into paintings in the style of famous artists.',
    category: 'Ideate',
    type: 'image',
    cover: '/images/styles/surrealism-art.jpg',
    samples: ['/images/styles/impressionism-art.jpg', '/images/styles/baroque-art.jpg'],
    steps: [
      { id: 'reference', label: 'Photo', type: 'image', required: true, hint: 'Upload the photo to transform' },
      { id: 'prompt', label: 'Artist/Style', type: 'text', required: true, hint: 'e.g. "In the style of Van Gogh\'s Starry Night" or "Monet water lilies style"' },
    ],
    defaultModel: 'flux',
    systemPrompt: 'Transform this photograph into a painting in the described artistic style. Preserve the subject matter while fully adopting the visual style.',
  },
  {
    id: 'landscape-generator',
    title: 'Landscape Generator',
    description: 'Create breathtaking landscape scenes — fantasy worlds, alien planets, serene nature.',
    category: 'Photography',
    type: 'image',
    cover: '/images/styles/renaissance-art.jpg',
    samples: ['/images/styles/surrealism-art.jpg'],
    steps: [
      { id: 'reference', label: 'Reference', type: 'image', required: false, hint: 'Upload a reference landscape (optional)' },
      { id: 'style', label: 'Style', type: 'style-picker', required: false },
      { id: 'prompt', label: 'Scene', type: 'text', required: true, hint: 'Describe your dream landscape in detail' },
    ],
    defaultModel: 'flux',
    systemPrompt: 'Generate a breathtaking, high-quality landscape scene with cinematic lighting and rich detail.',
  },
];

export const STYLE_PRESETS = [
  { id: 'dynamic', label: 'Dynamic', image: '/images/styles/digital-painting.jpg' },
  { id: 'cinematic', label: 'Cinematic', image: '/images/styles/baroque-art.jpg' },
  { id: 'cyberpunk', label: 'Cyberpunk', image: '/images/styles/cyberpunk-art.jpg' },
  { id: 'anime', label: 'Anime', image: '/images/styles/synthwave-art.jpg' },
  { id: 'impressionist', label: 'Impressionist', image: '/images/styles/impressionism-art.jpg' },
  { id: 'surreal', label: 'Surreal', image: '/images/styles/surrealism-art.jpg' },
  { id: 'minimalist', label: 'Minimalist', image: '/images/styles/minimalism-art.jpg' },
  { id: 'pop-art', label: 'Pop Art', image: '/images/styles/pop-art.jpeg' },
  { id: 'vaporwave', label: 'Vaporwave', image: '/images/styles/vaporwave-art.jpg' },
  { id: 'renaissance', label: 'Renaissance', image: '/images/styles/renaissance-art.jpg' },
  { id: 'art-nouveau', label: 'Art Nouveau', image: '/images/styles/art-nouveau.jpeg' },
  { id: 'abstract', label: 'Abstract', image: '/images/styles/abstract.jpeg' },
];
